name: sallm-ner
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  # Core ML/Python stack
  - python=3.12
  - pip
  - pytorch
  - pytorch-cuda=12.1
  - transformers
  - tokenizers
  - accelerate
  - datasets
  - wandb
  - pyyaml
  - scipy
  - numpy
  - pydantic
  - regex

  # Build dependencies for Mamba
  - gxx_linux-64

  # Dev tools
  - mypy
  - pytest
  - pip:
      - ruff

  # Pip-only or specific version dependencies
  - pip:
      - accelerate
      - types-pyyaml
      - tabulate
