tasks:
  - masakhaner_zu_prompt_1
  - masakhaner_zu_prompt_2
  - masakhaner_zu_prompt_3
  - masakhaner_zu_prompt_4
  - masakhaner_zu_prompt_5
fewshot: 0
batch_size: "auto:4"
apply_chat_template: true
