tasks:
  - sallm_masakhaner_tn_prompt_1_val
  - sallm_masakhaner_tn_prompt_2_val
  - sallm_masakhaner_tn_prompt_3_val
  - sallm_masakhaner_tn_prompt_4_val
  - sallm_masakhaner_tn_prompt_5_val
fewshot: 0
batch_size: "auto:4"
max_batch_size: 64
apply_chat_template: true
task_manager_kwargs:
  include_path:
    - src/conf/eval/lm_eval_tasks/masakhaner_validation
