tasks:
  - sallm_sib_xho_val_prompt_1
  - sallm_sib_xho_val_prompt_2
  - sallm_sib_xho_val_prompt_3
  - sallm_sib_xho_val_prompt_4
  - sallm_sib_xho_val_prompt_5
fewshot: 0
batch_size: "auto:4"
apply_chat_template: true
lm_eval_kwargs:
  max_batch_size: 64
  include_path:
    - src/conf/eval/lm_eval_tasks/sib_validation
