defaults:
  - defaults/datasets/t2x@_here_
  - _self_
mode: FINETUNE
wandb:
  project: sallm-ft
  name: llama-125m-t2x-xho
model:
  architecture: llama
  init_checkpoint: ${oc.env:SCRATCH}/masters/sallm/checkpoints/sallm-llama-125m/final_model
peft:
  method: lora
  kwargs:
    r: 16
    lora_alpha: 32
    lora_dropout: 0.05
dataset:
  subset: xho
  max_seq_length: 1024
tokenizer:
  path: ${oc.env:HOME}/masters/sallm/tokenizer/sallm_bpe_tokenizer
generation_decoding:
  strategy: beam
  num_beams: 5
  length_penalty: 1.0
  early_stopping: true
training:
  output_dir: ${oc.env:SCRATCH}/masters/sallm/checkpoints/ft_llama_125m_t2x_xho
  logging_dir: ${oc.env:SCRATCH}/masters/sallm/logs/ft_llama_125m_t2x_xho
  run_name: llama-125m-t2x-xho
  learning_rate: 0.00015373792550986017
  weight_decay: 0.1529293154724379
  adam_beta2: 0.95
  lr_scheduler_type: linear
  warmup_ratio: 0
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 16
  num_train_epochs: 4
  max_grad_norm: 1.0
  bf16: true
  gradient_checkpointing: false
  label_smoothing_factor: 0.05
  logging_steps: 10
  logging_first_step: true
  eval_strategy: epoch
  save_strategy: 'no'
  metric_for_best_model: eval_all_chrf
  greater_is_better: true
  dataloader_num_workers: 4
  eval_accumulation_steps: 1
  report_to: wandb
  ddp_find_unused_parameters: false
hub:
  enabled: true
  organization: anrilombard
  private: true
  push_adapter: true
  push_merged: false
