defaults:
  - defaults/datasets/masakhapos@_here_
  - _self_
mode: FINETUNE
wandb:
  project: sallm-ft
  name: mamba-125m-pos-zul
model:
  architecture: mamba2
  init_checkpoint: anrilombard/sallm-mamba-125m
peft:
  method: lora
  kwargs:
    r: 16
    lora_alpha: 32
    lora_dropout: 0.1
    target_modules:
      - in_proj
      - x_proj
dataset:
  subset: zul
  max_seq_length: 2048
tokenizer:
  path: ${oc.env:HOME}/masters/sallm/tokenizer/sallm_bpe_tokenizer
training:
  output_dir: ${oc.env:SCRATCH}/masters/sallm/checkpoints/ft_mamba_125m_pos_zul
  logging_dir: ${oc.env:SCRATCH}/masters/sallm/logs/ft_mamba_125m_pos_zul
  run_name: mamba-125m-pos-lora-zul
  learning_rate: 8.0e-05
  weight_decay: 0.01
  adam_beta2: 0.95
  max_grad_norm: 1.0
  gradient_accumulation_steps: 16
  lr_scheduler_type: cosine
  warmup_ratio: 0.03
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  eval_accumulation_steps: 1
  num_train_epochs: 15
  bf16: true
  gradient_checkpointing: true
  logging_steps: 10
  eval_strategy: epoch
  save_strategy: epoch
  dataloader_num_workers: 4
  report_to: wandb
  ddp_find_unused_parameters: false
  adam_beta1: 0.9
  save_total_limit: 1
  load_best_model_at_end: true
  metric_for_best_model: eval_all_token_accuracy
  greater_is_better: true
  early_stopping_patience: 3
  early_stopping_threshold: 0.001
hub:
  enabled: true
  organization: anrilombard
  private: true
  push_adapter: true
  push_merged: false
