defaults:
  - defaults/datasets/masakhaner@_here_
  - _self_
dataset:
  max_seq_length: 2048
  subset: null
  languages:
    - xho
hub:
  enabled: true
  organization: anrilombard
  private: true
  push_adapter: true
  push_merged: false
  base_model_id: anrilombard/sallm-xlstm-125m
mode: FINETUNE
model:
  architecture: xlstm
  init_checkpoint: anrilombard/sallm-xlstm-125m
peft:
  kwargs:
    lora_alpha: 32
    lora_dropout: 0.05
    r: 16
    target_modules:
      - q
      - k
      - v
      - out_proj
  method: lora
tokenizer:
  path: ${oc.env:HOME}/masters/sallm/tokenizer/sallm_bpe_tokenizer
training:
  adam_beta2: 0.95
  bf16: false
  dataloader_num_workers: 4
  ddp_find_unused_parameters: true
  eval_accumulation_steps: 1
  eval_strategy: epoch
  gradient_accumulation_steps: 16
  gradient_checkpointing: true
  learning_rate: 0.0004496585905434496
  logging_dir: ${oc.env:SCRATCH}/masters/sallm/logs/ft_xlstm_125m_ner_xho
  logging_steps: 10
  lr_scheduler_type: constant_with_warmup
  max_grad_norm: 1.0
  num_train_epochs: 20
  output_dir: ${oc.env:SCRATCH}/masters/sallm/checkpoints/ft_xlstm_125m_ner_xho
  per_device_eval_batch_size: 4
  per_device_train_batch_size: 4
  report_to: wandb
  run_name: xlstm-125m-ner-lora-finetune-xho
  save_strategy: 'no'
  warmup_ratio: 0
  weight_decay: 0.13449041980438445
wandb:
  name: xlstm-125m-ner-xho
  project: sallm-ft
