defaults:
  - defaults/datasets/afrihg@_here_
  - _self_
mode: FINETUNE
wandb:
  project: sallm-ft
  name: xlstm-125m-afrihg-all
model:
  architecture: xlstm
  init_checkpoint: anrilombard/sallm-xlstm-125m
peft:
  method: lora
  kwargs:
    r: 256
    lora_alpha: 512
    lora_dropout: 0.1
    target_modules:
      - q
      - k
      - v
      - out_proj
      - embeddings
dataset:
  subset: null
  max_seq_length: 1024
tokenizer:
  path: ${oc.env:HOME}/masters/sallm/tokenizer/sallm_bpe_tokenizer
training:
  output_dir: ${oc.env:SCRATCH}/masters/sallm/checkpoints/ft_xlstm_125m_afrihg_all
  logging_dir: ${oc.env:SCRATCH}/masters/sallm/logs/ft_xlstm_125m_afrihg_all
  run_name: xlstm-125m-afrihg-all
  learning_rate: 0.0001
  weight_decay: 0.1
  adam_beta2: 0.95
  lr_scheduler_type: cosine
  warmup_ratio: 0.1
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
  num_train_epochs: 5
  max_grad_norm: 1.0
  bf16: false
  gradient_checkpointing: true
  logging_steps: 10
  logging_first_step: true
  eval_strategy: epoch
  save_strategy: 'no'
  metric_for_best_model: eval_all_chrf
  greater_is_better: true
  dataloader_num_workers: 4
  eval_accumulation_steps: 1
  report_to: wandb
  ddp_find_unused_parameters: true
hub:
  enabled: true
  organization: anrilombard
  private: true
  push_adapter: true
  push_merged: false
  base_model_id: anrilombard/sallm-xlstm-125m
